'use client';

import { motion } from 'framer-motion';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import type { Project, Service } from '@/lib/types';
import { useCart } from './cart';
import { useEnquiryModal } from './enquiry-modal-context';
import { SkeletonCard } from './SkeletonCard';
import { AdminLoginModal } from './AdminLoginModal';
import { AnimatedCount, EnquiryIconButton, RequestIcon } from './EnquiryIconButton';

export const scrollToSection = (id: string) => {
  const target = document.getElementById(id);
  if (target) { target.scrollIntoView({ behavior: 'smooth', block: 'start' }); window.history.replaceState(null, '', `#${id}`); }
};

export function PublicHeader() {
  const router = useRouter(), pathname = usePathname(); const { totalItems, ready } = useCart(); const { openEnquiry } = useEnquiryModal(); const [open, setOpen] = useState(false), [active, setActive] = useState('home'), [adminOpen, setAdminOpen] = useState(false);
  const links: [string, string][] = [['Home','home'], ['About','about'], ['Services','services'], ['Advertisement','projects'], ['Contact','contact']];
  const go = (id: string) => { setOpen(false); setActive(id); if (pathname !== '/') { router.push(`/#${id}`); return; } scrollToSection(id); if (!document.getElementById(id)) setTimeout(() => scrollToSection(id), 180); };
  useEffect(() => { if (pathname !== '/') return; const ids = ['home','about','services','projects','contact','enquiry']; const observer = new IntersectionObserver(entries => { const hit = entries.filter(entry => entry.isIntersecting).sort((a,b) => b.intersectionRatio-a.intersectionRatio)[0]; if (hit) setActive(hit.target.id === 'enquiry' ? 'contact' : hit.target.id); }, { rootMargin: '-38% 0px -50% 0px', threshold: [.05,.25] }); ids.forEach(id => document.getElementById(id) && observer.observe(document.getElementById(id)!)); const hash = location.hash.slice(1); if (hash) setTimeout(() => scrollToSection(hash), 250); return () => observer.disconnect(); }, [pathname]);
  const count = ready ? totalItems : 0;
  return <><header className="sticky top-0 z-40 border-b border-white/10 bg-ink/85 text-white backdrop-blur-xl"><div className="wrap flex h-18 items-center justify-between gap-4"><button onClick={() => go('home')} className="text-left font-black tracking-[.18em]">SCCL<span className="text-gold">.</span></button><nav className="hidden items-center gap-2 text-sm md:flex">{links.map(([label,id]) => <button key={id} onClick={() => go(id)} className={`rounded-full px-3 py-2 transition active:scale-95 ${active === id ? 'bg-white/10 text-gold' : 'text-slate-200 hover:bg-white/10 hover:text-gold'}`}>{label}</button>)}</nav><div className="flex items-center gap-2"><button onClick={openEnquiry} className="enquiry-cart-button" aria-label={`Enquiry cart, ${count} selected services`} title="Enquiry cart"><RequestIcon /><AnimatedCount value={count} /></button><button onClick={() => setOpen(value => !value)} className="rounded p-2 md:hidden" aria-label="Open navigation">☰</button></div></div>{open && <nav className="wrap flex flex-col gap-1 border-t border-white/10 py-3 md:hidden">{links.map(([label,id]) => <button key={id} onClick={() => go(id)} className="rounded px-2 py-2 text-left hover:bg-white/10">{label}</button>)}</nav>}</header>{count > 0 && <button onClick={openEnquiry} className="floating-enquiry-cart" aria-label={`View ${count} selected services`}><RequestIcon /><span className="hidden sm:inline">Your enquiry</span><AnimatedCount value={count} /></button>}<button onClick={() => setAdminOpen(true)} className="fixed bottom-5 left-5 z-30 grid h-11 w-11 place-items-center rounded-full bg-ink text-gold shadow-xl ring-1 ring-white/20" aria-label="Admin access">⌑</button><AdminLoginModal open={adminOpen} onClose={() => setAdminOpen(false)} /></>;
}
export function SectionHeader({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) { return <div className="mb-10 max-w-2xl"><p className="mb-2 text-sm font-bold uppercase tracking-[.2em] text-gold">{eyebrow}</p><h2 className="text-3xl font-bold text-ink md:text-5xl">{title}</h2>{text && <p className="mt-4 text-slate-600">{text}</p>}</div>; }
export function Placeholder({ label, kind = 'image' }: { label: string; kind?: string }) { return <div className={`placeholder-art ${kind}`}><span>◇</span><p>{label}</p></div>; }
export function ServiceCard({ service, onDetails, onAdded }: { service: Service; onDetails?: (service: Service) => void; onAdded?: (newItem: boolean) => void }) { const { add, hasService, countForService } = useCart(); const active = hasService(service.id); const addItem = () => { add(service); onAdded?.(!active); }; return <motion.article initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} whileHover={{ y: -7 }} className="card group"><div className="aspect-[4/3] bg-ink/10">{service.image ? <img src={service.image} alt={service.title} className="h-full w-full object-cover" /> : <Placeholder label={service.title} />}</div><div className="p-6"><p className="text-xs font-bold uppercase text-gold">{service.category || 'Service'}</p><h3 className="mt-2 text-xl font-bold">{service.title}</h3><p className="mt-2 line-clamp-3 text-sm text-slate-600">{service.short_description}</p><div className="mt-5 flex items-center justify-between"><button onClick={() => onDetails?.(service)} className="text-sm font-bold hover:text-gold">View details</button><EnquiryIconButton active={active} count={countForService(service.id)} label={active ? `${service.title} is already in your enquiry` : `Add ${service.title} to enquiry`} onClick={addItem} /></div></div></motion.article>; }
export function ProjectCard({ project }: { project: Project }) { return <motion.article layout initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} whileHover={{ y: -5 }} className="card"><div className="aspect-[4/3] bg-ink/10">{project.image ? <img src={project.image} alt={project.title} className="h-full w-full object-cover" /> : <Placeholder label={project.title} />}</div><div className="p-5"><div className="flex justify-between gap-2"><h3 className="font-bold">{project.title}</h3><span className="text-xs uppercase text-gold">{project.category}</span></div><p className="mt-2 text-sm text-slate-600">{project.location || project.status}</p></div></motion.article>; }
export function SkeletonGrid({ count = 3 }: { count?: number }) { return <div className="grid gap-6 md:grid-cols-3">{Array.from({ length: count }, (_, i) => <SkeletonCard key={i} />)}</div>; }
