'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { api } from '@/lib/api';
import type { Project, Service } from '@/lib/types';
import { Loader } from '@/components/Loader';
import { ProjectCard, SectionHeader, ServiceCard, scrollToSection } from '@/components/site';
import { useCart } from '@/components/cart';

const categories = ['all', 'completed', 'ongoing', 'daily', 'featured'];
const icons: Record<string, string> = { vision: '◉', mission: '↗', focus: '◇', value: '✦' };

export default function HomePage() {
  const [data, setData] = useState<any>(); const [failed, setFailed] = useState(false); const [category, setCategory] = useState('all'); const [detail, setDetail] = useState<Service | null>(null);
  useEffect(() => { api<any>('/home/').then(setData).catch(() => setFailed(true)); }, []);
  const projects = useMemo(() => (data?.projects || data?.featured_projects || []).filter((item: Project) => category === 'all' || (category === 'featured' ? item.is_featured || item.category === 'featured' : item.category === category)), [data, category]);
  if (failed) return <main className="wrap section"><div className="card p-8"><h1 className="text-2xl font-bold">We could not load the site content.</h1><p className="mt-2 text-slate-600">Please check the CMS connection and refresh.</p></div></main>;
  if (!data) return <Loader />;
  const hero = data?.hero; const site = data?.site_settings; const services: Service[] = data?.services || data?.featured_services || [];
  return <main>
    <section id="home" className="relative isolate min-h-[650px] overflow-hidden bg-ink text-white"><div className="absolute inset-0">{hero?.background_image && <img src={hero.background_image} alt="" className="h-full w-full object-cover opacity-40" />}<div className="absolute inset-0 bg-gradient-to-r from-ink via-ink/80 to-ink/35" /></div><div className="wrap relative flex min-h-[650px] items-center py-28"><div className="max-w-4xl"><motion.p initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="mb-5 font-bold uppercase tracking-[.24em] text-gold">{hero?.subtitle || 'Engineering · Construction · Consultancy'}</motion.p><motion.h1 initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .1 }} className="text-5xl font-black leading-[.95] md:text-7xl">{hero?.title || 'Infrastructure built with conviction.'}</motion.h1><motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .25 }} className="mt-7 max-w-2xl text-lg text-slate-200">{hero?.description || 'A detail-led construction and consultancy partner for ambitious, enduring work.'}</motion.p><div className="mt-9 flex flex-wrap gap-3"><button onClick={() => scrollToSection('services')} className="btn btn-gold">{hero?.primary_button_text || 'Explore services'}</button><button onClick={() => scrollToSection('contact')} className="btn border border-white/30 text-white">{hero?.secondary_button_text || 'Request a consultation'}</button></div></div></div></section>
    <section id="about" className="section bg-white"><div className="wrap grid items-center gap-12 lg:grid-cols-2"><motion.div initial={{ opacity: 0, x: -25 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }}><SectionHeader eyebrow="Who we are" title={data?.about?.title || 'A disciplined partner from brief to handover.'} /><p className="whitespace-pre-line text-lg leading-8 text-slate-600">{data?.about?.description || 'We combine practical construction knowledge, transparent project stewardship and technical clarity.'}</p>{data?.about?.bullet_points?.length > 0 && <ul className="mt-7 grid gap-3 sm:grid-cols-2">{data.about.bullet_points.map((point: string) => <li className="rounded-xl bg-sand px-4 py-3 font-semibold" key={point}>✓ {point}</li>)}</ul>}</motion.div><div className="aspect-[5/4] overflow-hidden rounded-3xl bg-ink/10">{data?.about?.image && <img src={data.about.image} alt="Our team at work" className="h-full w-full object-cover" />}</div></div></section>
    <section className="section"><div className="wrap grid gap-5 md:grid-cols-3">{(data?.info_cards || []).slice(0, 3).map((card: any, index: number) => <motion.article initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} transition={{ delay: index * .08 }} viewport={{ once: true }} className="card p-7" key={card.id}><span className="text-3xl text-gold">{icons[card.type] || '✦'}</span><h3 className="mt-5 text-2xl font-bold">{card.title}</h3><p className="mt-3 text-slate-600">{card.description}</p></motion.article>)}</div></section>
    <section id="services" className="section bg-white"><div className="wrap"><SectionHeader eyebrow="Capabilities" title="Technical capability, carefully delivered" text="Select the services relevant to your project and send one focused enquiry." /><div className="grid gap-6 md:grid-cols-3">{services.map(service => <ServiceCard key={service.id} service={service} onDetails={setDetail} />)}</div></div></section>
    <section className="section bg-ink text-white"><div className="wrap grid gap-8 text-center sm:grid-cols-2 lg:grid-cols-4">{(data?.stats || []).map((stat: any) => <Stat key={stat.id} value={stat.value} suffix={stat.suffix} label={stat.label} />)}</div></section>
    <section id="projects" className="section"><div className="wrap"><SectionHeader eyebrow="Selected work" title="Projects with lasting value" /><div className="mb-8 flex flex-wrap gap-2">{categories.map(item => <button key={item} onClick={() => setCategory(item)} className={`rounded-full px-4 py-2 text-sm font-semibold capitalize transition ${category === item ? 'bg-ink text-white' : 'bg-white hover:bg-gold/20'}`}>{item}</button>)}</div><motion.div layout className="grid gap-6 md:grid-cols-3">{projects.map((project: Project) => <ProjectCard key={project.id} project={project} />)}</motion.div>{!projects.length && <p className="rounded-xl bg-white p-6 text-slate-600">No projects in this category yet.</p>}</div></section>
    <section id="team" className="section bg-white"><div className="wrap"><SectionHeader eyebrow="Our people" title="Experience you can speak to" /><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{(data?.team || []).map((member: any) => <motion.article whileHover={{ y: -5 }} className="card" key={member.id}><div className="aspect-square bg-slate-100">{member.photo && <img src={member.photo} alt={member.name} className="h-full w-full object-cover" />}</div><div className="p-6"><h3 className="text-xl font-bold">{member.name}</h3><p className="mt-1 text-sm font-semibold text-gold">{member.position}</p>{member.message && <p className="mt-3 text-sm text-slate-600">{member.message}</p>}</div></motion.article>)}</div></div></section>
    <ContactSection site={site} />
    <footer className="bg-ink py-12 text-slate-300"><div className="wrap grid gap-8 md:grid-cols-3"><div><p className="font-black tracking-[.18em] text-white">{site?.company_name || 'SCCL'}<span className="text-gold">.</span></p><p className="mt-4 text-sm">{site?.footer_text || 'Built with technical care and lasting accountability.'}</p></div><div className="text-sm"><p>{site?.address || site?.location}</p><p className="mt-2">{site?.primary_phone} · {site?.email}</p><p className="mt-2">{site?.working_days} {site?.working_hours}</p></div><div className="md:text-right"><a className="text-sm text-gold hover:text-white" href="/admin/login">Admin login</a></div></div></footer>
    <AnimatePresence>{detail && <div className="fixed inset-0 z-50 grid place-items-center bg-ink/70 p-4"><motion.div initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} className="max-h-[85vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-7"><div className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase text-gold">{detail.category}</p><h2 className="mt-1 text-2xl font-bold">{detail.title}</h2></div><button onClick={() => setDetail(null)} aria-label="Close">✕</button></div><p className="mt-5 whitespace-pre-line text-slate-600">{detail.full_description}</p><button className="btn btn-gold mt-7" onClick={() => { scrollToSection('enquiry'); setDetail(null); }}>Request this service</button></motion.div></div>}</AnimatePresence>
  </main>;
}

function Stat({ value, suffix, label }: { value: number; suffix?: string; label: string }) { const [shown, setShown] = useState(0); useEffect(() => { let frame = 0; const start = performance.now(); const tick = (now: number) => { const progress = Math.min((now - start) / 900, 1); setShown(Math.round(value * progress)); if (progress < 1) frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [value]); return <div><strong className="text-5xl text-gold">{shown}{suffix}</strong><p className="mt-3 text-sm font-bold uppercase tracking-wider text-slate-300">{label}</p></div>; }

function ContactSection({ site }: { site: any }) { const { items, remove, updateNote, clear } = useCart(); const [notice, setNotice] = useState(''); const [sending, setSending] = useState(false); async function submit(event: FormEvent<HTMLFormElement>, enquiry: boolean) { event.preventDefault(); if (enquiry && !items.length) return; setSending(true); setNotice(''); try { const fields = Object.fromEntries(new FormData(event.currentTarget)); await api(enquiry ? '/enquiries/' : '/contact-messages/', { method: 'POST', body: JSON.stringify(enquiry ? { ...fields, items: items.map(({ service, note, quantity }) => ({ service, note, quantity })) } : fields) }); event.currentTarget.reset(); if (enquiry) clear(); setNotice('Thank you. We have received your message.'); } catch (error: any) { setNotice(error.message); } finally { setSending(false); } }
return <section id="contact" className="section"><div className="wrap grid gap-10 lg:grid-cols-2"><div><SectionHeader eyebrow="Contact" title="Let’s discuss your next project." /><p className="mb-6 text-slate-600">{site?.location} · {site?.primary_phone} · {site?.email}</p><form className="space-y-3" onSubmit={event => submit(event, false)}><input className="input" name="full_name" required placeholder="Full name" /><input className="input" name="phone" placeholder="Phone" /><input className="input" type="email" name="email" placeholder="Email" /><input className="input" name="subject" placeholder="Subject" /><textarea className="input min-h-32" name="message" required placeholder="How can we help?" /><button className="btn btn-dark" disabled={sending}>{sending ? 'Sending…' : 'Send message'}</button></form></div><div id="enquiry" className="card p-7"><p className="font-bold uppercase tracking-widest text-gold">Request quotation</p><h2 className="mt-2 text-2xl font-bold">Enquiry cart ({items.length})</h2>{items.length ? <ul className="my-5 space-y-3">{items.map(item => <li className="rounded-xl bg-sand p-3" key={item.service}><div className="flex justify-between"><b>{item.service_title_snapshot}</b><button type="button" onClick={() => remove(item.service)}>×</button></div><input className="input mt-2" value={item.note} onChange={event => updateNote(item.service, event.target.value)} placeholder="Note for this service" /></li>)}</ul> : <p className="my-5 text-sm text-slate-600">Add services above to build your enquiry.</p>}<form className="space-y-3" onSubmit={event => submit(event, true)}><input className="input" name="full_name" required placeholder="Full name" /><input className="input" name="phone" required placeholder="Phone" /><input className="input" type="email" name="email" placeholder="Email (optional)" /><input className="input" name="location" required placeholder="Project location" /><select className="input" name="preferred_contact_method" defaultValue="Phone"><option>Phone</option><option>Email</option><option>WhatsApp</option></select><textarea className="input min-h-24" name="message" placeholder="Tell us about the project" /><button disabled={!items.length || sending} className="btn btn-gold disabled:opacity-40">{sending ? 'Submitting…' : 'Submit enquiry'}</button></form></div></div>{notice && <p className="fixed bottom-5 right-5 z-50 rounded-lg bg-ink p-4 text-white">{notice}</p>}</section>; }
